In [22]:
#Exercici 1_Crea una funció que donat un Array d’una dimensió, 
#et faci un resum estadístic bàsic de les dades. 
#Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.
import numpy as np
arr = np.array([1,2,3,4,5])
newarr = np.sum([arr])
print("the average value is:",newarr/5)

the average value is: 3.0


In [36]:
#Exercici 2_Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.
from numpy import random
x = random.randint(100, size=(10, 10))
print(x)

[[ 1 86 70 62 99 82 89 19  9 64]
 [98 10 65 89 85  0 86 77 46 97]
 [86 16  0 67 21 23 17 31 24  4]
 [95 16 56 16 77 25  6 96 90 63]
 [42 93 99 44 57 70 54 99 67 75]
 [11 36 11 63 77 42 63 19 83 38]
 [24  7 78 51 60 38 26 14 77  0]
 [58 11 66 13 42 61  2 38 90 77]
 [90 42 28 58 40 87 70 79 48 32]
 [50 39 48 11 42 76  5 14 67 55]]


In [34]:
#Exercici 3_Crea una funció que donada una taula de dues dimensions, 
#et calculi els totals per fila i els totals per columna.
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)
newarr1 = np.sum([arr],axis=1)
newarr2 = np.sum([arr],axis=2)
print("els totals per fila es",newarr2)
print("els totals per columna es",newarr1)

[[1 2 3]
 [4 5 6]]
els totals per fila es [[ 6 15]]
els totals per columna es [[5 7 9]]


In [7]:
#Exercici 4_Implementa manualment una funció que calculi el coeficient de correlació. 
#Informa’t-en sobre els seus usos i interpretació.

In [41]:
x_simple = np.array([1,2,3,4,5])
y_simple = np.array([1,4,4,5,6])
rho = np.corrcoef(x_simple, y_simple)

print(rho)

[[1.         0.92966968]
 [0.92966968 1.        ]]
