In [68]:
#Exercici 1_Crea una funció que donat un Array d’una dimensió, 
#et faci un resum estadístic bàsic de les dades. 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

data = np.array([1,2,6,10,15])
print('the array dimension is', data.ndim)
print('the sum is', data.sum())
print('the minimum is', data.min())
print('the maximum is', data.max())
print('the mean value is', data.mean())
print('the standard deviation is', np.std(data).round(2))

the array dimension is 1
the sum is 34
the minimum is 1
the maximum is 15
the mean value is 6.8
the standard deviation is 5.19


In [71]:
#Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.
arr1 = np.array(([1,2,3,4,5],[6,7,8,9,10]))
if arr1.ndim > 1:
 print("cuidado! arr1 té mes d'una dimensió.")

cuidado! arr1 té mes d'una dimensió.


In [2]:
#Exercici 2_Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.
from numpy import random
x = random.randint(100, size=(10, 10))
print(x)

[[92 83 47 43 15 85 97 29 90 12]
 [ 3 86 20 12 90 33 33 53 99 69]
 [91 75 67 51 50 32 43 98 56 71]
 [58  0 74 34 89 83 72 49 81  5]
 [51 75 69 42 75 68 32 48 63 23]
 [35 19 73 16  5 68 59 97 55 51]
 [89 65 37  0 42 33  6 62 80 53]
 [45  8 56 95 83 47 39 52 31 38]
 [50 12 71 49 87 19 88 90 83 60]
 [53 60 58  6  0 27 58 33 45 98]]


In [6]:
#Exercici 3_Crea una funció que donada una taula de dues dimensions, 
#et calculi els totals per fila i els totals per columna.
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr)
newarr1 = np.sum([arr],axis=1)
newarr2 = np.sum([arr],axis=2)
print("els totals per fila es",newarr2)
print("els totals per columna es",newarr1)

[[1 2 3]
 [4 5 6]]
els totals per fila es [[ 6 15]]
els totals per columna es [[5 7 9]]


In [4]:
#Exercici 4_Implementa manualment una funció que calculi el coeficient de correlació. 
#Informa’t-en sobre els seus usos i interpretació.

In [5]:
x_simple = np.array([1,2,3,4,5])
y_simple = np.array([1,4,4,5,6])
rho = np.corrcoef(x_simple, y_simple)

print(rho)

[[1.         0.92966968]
 [0.92966968 1.        ]]
